# Generated by Django 5.0.3 on 2024-07-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0037_delete_accommodationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='words',
            field=models.TextField(blank=True),
        ),
    ]
