# Generated by Django 4.2.11 on 2024-07-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0037_delete_accommodationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accommodation_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='travel_destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
